/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Basket;
import Model.DBHandler;
import Model.Pants;
import Model.Product;
import Model.Shirt;
import Model.TShirt;
import java.util.ArrayList;

/**
 * @author Jakob Ferdinandsen
 * @author Morten Ricki Rasmussen
 */
public class GUI extends javax.swing.JFrame {

    private double totalAmount;
    private ArrayList<TShirt> tShirts;
    private ArrayList<Pants> pants;
    private ArrayList<Shirt> shirts;
    private Basket kurv;

    /**
     * Creates new form GUI
     */
    public void calculateAmount() {
        String totalAmount = kurv.calculateTotalAmount() + " DKK";
        headerBeløb.setText(totalAmount);
    }

    public GUI() {
        initComponents();
        //--------------------------------------------------------------------------
        //Sætter titlen på programmet
        //--------------------------------------------------------------------------
        super.setTitle("Næstveds Tøjmagasin");

        basketPanel.setVisible(false);
        checkoutPanel.setVisible(false);

        //--------------------------------------------------------------------------
        //Laver et basket Objekt og b
        //--------------------------------------------------------------------------
        kurv = new Basket();

        totalAmount = kurv.calculateTotalAmount();
        headerBeløb.setText(totalAmount + "0 DKK");

        //--------------------------------------------------------------------------
        // Initialisere produkt ArrayLists
        //--------------------------------------------------------------------------
        tShirts = new ArrayList<>();
        pants = new ArrayList<>();
        shirts = new ArrayList<>();

        DBHandler.loadArrayLists(tShirts, pants, shirts);

        //--------------------------------------------------------------------------
        // Fylder de forskellige comboboxe op med data
        //--------------------------------------------------------------------------
        for (TShirt tShirt : tShirts) {
            tShirtCombo.addItem(tShirt);
        }
        for (Shirt shirt : shirts) {
            shirtCombo.addItem(shirt);
        }
        for (int i = 0; i < pants.size(); i++) {
            pantsCombo.addItem(pants.get(i));   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        headerBeløb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        mainPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        tShirtCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        tShirtSizeCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        addTShirtToBasket = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tShirtPriceLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        shirtSizeCombo = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        shirtCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        shirtPriceLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addShirtToBasket = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pantsSizeCombo = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        pantsCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        pantsPriceLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addPantsToBasket = new javax.swing.JButton();
        basketPanel = new javax.swing.JPanel();
        basketCheckoutButton = new javax.swing.JButton();
        basketBackButton = new javax.swing.JButton();
        checkoutPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        headerBeløb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        headerBeløb.setText("0 DKK");
        headerBeløb.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel2.setText("Kurv:");

        jLabel3.setText("Velkommen");

        jButton1.setText("Gå til kurv");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(headerBeløb, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(headerBeløb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tShirtCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        tShirtCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tShirtComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Vælg Produkt");

        tShirtSizeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        tShirtSizeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tShirtSizeComboActionPerformed(evt);
            }
        });

        jLabel7.setText("Vælg Størrelse");

        addTShirtToBasket.setText("Læg i Kurv");
        addTShirtToBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTShirtToBasketActionPerformed(evt);
            }
        });

        jLabel8.setText("Pris:");

        tShirtPriceLabel.setText("0,00 ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(245, 245, 245))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tShirtCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(86, 86, 86)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tShirtPriceLabel)
                            .addComponent(jLabel8)))
                    .addComponent(tShirtSizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(329, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTShirtToBasket)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tShirtCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tShirtPriceLabel))
                .addGap(70, 70, 70)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tShirtSizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(addTShirtToBasket)
                .addContainerGap())
        );

        mainPane.addTab("T-shirts", jPanel2);

        shirtSizeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        shirtSizeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shirtSizeComboActionPerformed(evt);
            }
        });

        jLabel11.setText("Vælg Størrelse");

        shirtCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        shirtCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shirtComboActionPerformed(evt);
            }
        });

        jLabel6.setText("Vælg Produkt");

        shirtPriceLabel.setText("0,00 ");

        jLabel12.setText("Pris:");

        addShirtToBasket.setText("Læg i Kurv");
        addShirtToBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShirtToBasketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(245, 245, 245))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(shirtCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(86, 86, 86)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shirtPriceLabel)
                            .addComponent(jLabel12)))
                    .addComponent(shirtSizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(329, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addShirtToBasket)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shirtCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shirtPriceLabel))
                .addGap(70, 70, 70)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shirtSizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(addShirtToBasket)
                .addContainerGap())
        );

        mainPane.addTab("Skjorter", jPanel3);

        pantsSizeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        pantsSizeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantsSizeComboActionPerformed(evt);
            }
        });

        jLabel9.setText("Vælg Størrelse");

        pantsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        pantsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantsComboActionPerformed(evt);
            }
        });

        jLabel5.setText("Vælg Produkt");

        pantsPriceLabel.setText("0,00 ");

        jLabel10.setText("Pris:");

        addPantsToBasket.setText("Læg i Kurv");
        addPantsToBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPantsToBasketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(245, 245, 245))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pantsCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(86, 86, 86)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pantsPriceLabel)
                            .addComponent(jLabel10)))
                    .addComponent(pantsSizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(329, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addPantsToBasket)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pantsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pantsPriceLabel))
                .addGap(70, 70, 70)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantsSizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(addPantsToBasket)
                .addContainerGap())
        );

        mainPane.addTab("Bukser", jPanel1);

        basketPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        basketCheckoutButton.setText("Bestil");
        basketCheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketCheckoutButtonActionPerformed(evt);
            }
        });

        basketBackButton.setText("Tilbage til kataloget");
        basketBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basketPanelLayout = new javax.swing.GroupLayout(basketPanel);
        basketPanel.setLayout(basketPanelLayout);
        basketPanelLayout.setHorizontalGroup(
            basketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basketPanelLayout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addGroup(basketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(basketCheckoutButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(basketBackButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        basketPanelLayout.setVerticalGroup(
            basketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basketBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addComponent(basketCheckoutButton)
                .addContainerGap())
        );

        checkoutPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setText("jButton2");

        javax.swing.GroupLayout checkoutPanelLayout = new javax.swing.GroupLayout(checkoutPanel);
        checkoutPanel.setLayout(checkoutPanelLayout);
        checkoutPanelLayout.setHorizontalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jButton2)
                .addContainerGap(365, Short.MAX_VALUE))
        );
        checkoutPanelLayout.setVerticalGroup(
            checkoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutPanelLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jButton2)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(basketPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(checkoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane)
                .addContainerGap())
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(basketPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(checkoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1.setLayer(mainPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(basketPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(checkoutPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void basketBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketBackButtonActionPerformed
        basketPanel.setVisible(false);
        mainPane.setVisible(true);
    }//GEN-LAST:event_basketBackButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainPane.setVisible(false);
        basketPanel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tShirtSizeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tShirtSizeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tShirtSizeComboActionPerformed

    private void tShirtComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tShirtComboActionPerformed
        tShirtSizeCombo.removeAllItems();

        TShirt tshirt = (TShirt) tShirtCombo.getSelectedItem();

        for (int i = 0; i < tshirt.getSizesSize(); i++) {
            tShirtSizeCombo.addItem(tshirt.getSizes(i));
        }

        tShirtPriceLabel.setText(tshirt.getPrice() + " DKK");
    }//GEN-LAST:event_tShirtComboActionPerformed

    private void pantsSizeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantsSizeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantsSizeComboActionPerformed

    private void pantsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantsComboActionPerformed
        pantsSizeCombo.removeAllItems();

        Pants pants = (Pants) pantsCombo.getSelectedItem();

        for (int i = 0; i < pants.getSizesSize(); i++) {
            pantsSizeCombo.addItem(pants.getSizes(i));
        }

        pantsPriceLabel.setText(pants.getPrice() + " DKK");
    }//GEN-LAST:event_pantsComboActionPerformed

    private void shirtSizeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shirtSizeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shirtSizeComboActionPerformed

    private void shirtComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shirtComboActionPerformed
        shirtSizeCombo.removeAllItems();

        Shirt shirt = (Shirt) shirtCombo.getSelectedItem();

        for (int i = 0; i < shirt.getSizesSize(); i++) {
            shirtSizeCombo.addItem(shirt.getSizes(i));
        }

        shirtPriceLabel.setText(shirt.getPrice() + " DKK");
    }//GEN-LAST:event_shirtComboActionPerformed

    private void addTShirtToBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTShirtToBasketActionPerformed
        if (tShirtCombo.getSelectedIndex() != 0){
            kurv.addItem((Product) tShirtCombo.getSelectedItem());
            calculateAmount();
        }
    }//GEN-LAST:event_addTShirtToBasketActionPerformed

    private void addShirtToBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShirtToBasketActionPerformed
        if (shirtCombo.getSelectedIndex() != 0){
            kurv.addItem((Product) shirtCombo.getSelectedItem());
            calculateAmount();
        }
    }//GEN-LAST:event_addShirtToBasketActionPerformed

    private void addPantsToBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPantsToBasketActionPerformed
        if (pantsCombo.getSelectedIndex() != 0){
            kurv.addItem((Product) pantsCombo.getSelectedItem());
            calculateAmount();
        }
    }//GEN-LAST:event_addPantsToBasketActionPerformed

    private void basketCheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketCheckoutButtonActionPerformed
        basketPanel.setVisible(false);
        checkoutPanel.setVisible(true);
    }//GEN-LAST:event_basketCheckoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPantsToBasket;
    private javax.swing.JButton addShirtToBasket;
    private javax.swing.JButton addTShirtToBasket;
    private javax.swing.JButton basketBackButton;
    private javax.swing.JButton basketCheckoutButton;
    private javax.swing.JPanel basketPanel;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JLabel headerBeløb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane mainPane;
    private javax.swing.JComboBox pantsCombo;
    private javax.swing.JLabel pantsPriceLabel;
    private javax.swing.JComboBox pantsSizeCombo;
    private javax.swing.JComboBox shirtCombo;
    private javax.swing.JLabel shirtPriceLabel;
    private javax.swing.JComboBox shirtSizeCombo;
    private javax.swing.JComboBox tShirtCombo;
    private javax.swing.JLabel tShirtPriceLabel;
    private javax.swing.JComboBox tShirtSizeCombo;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
