/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Basket;
import Model.Product;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Morten Ricki Rasmussen
 */
public class ProductShow extends javax.swing.JPanel {

    private String productName;
    private String color;
    private ArrayList sizes;
    private String price;
    private ArrayList products;
    private Basket kurv;
    private JLabel headerPrice;
    private String totalAmount;

    /**
     * Creates new form ProductShow
     */
    public ProductShow(String productName, String color, ArrayList sizes, String price, ArrayList product, Basket kurv, JLabel headerPrice, String totalAmount) {
        this.productName = productName;
        this.color = color;
        this.sizes = sizes;
        this.price = price;
        this.products = product;
        this.kurv = kurv;
        this.headerPrice = headerPrice;
        this.totalAmount = totalAmount;
        initComponents();
        fillData(productName, color, sizes, price);
    }

    //--------------------------------------------------------------------------
    // fillData fylder data på de forskellige labels osv.
    //--------------------------------------------------------------------------
    public void fillData(String productName, String color, ArrayList sizes, String price) {
        productNameLabel.setText(productName);
        colorLabel.setText(color);
        for (int i = 0; i < sizes.size(); i++) {
            sizeComboBox.addItem(sizes.get(i));
        }
        priceLabel.setText(price + " DKK");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productNameLabel = new javax.swing.JLabel();
        sizeComboBox = new javax.swing.JComboBox();
        priceLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(660, 120));
        setMinimumSize(new java.awt.Dimension(660, 120));
        setPreferredSize(new java.awt.Dimension(660, 120));

        productNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        productNameLabel.setText("Hvid smoking Skjorte");

        priceLabel.setText("0000DK");

        jLabel2.setText("Pris:");

        colorLabel.setText("Farve: ");

        jButton1.setText("Tilføj til kurv");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(colorLabel)
                                .addGap(569, 569, 569))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(productNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addGap(36, 36, 36)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameLabel)
                    .addComponent(sizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorLabel)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //--------------------------------------------------------------------------
        // Tilføjer produkter til kurven
        //--------------------------------------------------------------------------
        int index = 0;
        for (int i = 0; i < products.size(); i++) {
            Product p = (Product) products.get(i);
            if (p.getName().equals(productName)) {
                index = i;
            }
        }

        String selectedSize = (String) sizeComboBox.getSelectedItem();
        kurv.addItem((Product) products.get(index), selectedSize);
        totalAmount = kurv.calculateTotalAmount();
        headerPrice.setText(totalAmount + " DKK");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel colorLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JComboBox sizeComboBox;
    // End of variables declaration//GEN-END:variables

}
